### PR TITLE
upgrade application CRD to v1

### PR DESCRIPTION
**Pull request by xiangjingli**
Signed-off-by: Xiangjing Li <xiangli@redhat.com>

https://github.com/open-cluster-management/backlog/issues/10642

### CODE REVIEW

**Comment by xiangjingli** [comment]
@mikeshng  @rokej  Please hold the PR, Just found the deployable CRD have some other issues, that caused the failure of the unit test in deployable repo, though the unit test in subscription has passed. I will come up with new fix tomorrow.

**Comment by mikeshng** [comment]
reopening to see if hung prow jobs are fixed.

**Pull request merged**
